name: base # mzbsuite
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.25
  - pandas=1.5.3
  # - yaml==0.2.5
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision
  - pytorch-lightning=2.0.3
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - scikit-image=0.20.0
  - pip
  - pip:
    - pyyaml==6.0
    - wandb==0.15.4
    - opencv-python==4.8.0
    - segmentation_models_pytorch==0.3.3
