name: mzbfull
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohttp=3.8.1=py38h0a891b7_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.0=py38hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py38h578d9bd_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.5.0=py38h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.3.0=py38h0a891b7_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.6=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=4.11.4=py38h578d9bd_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.9.1=py38h06a4308_0
  - ipython=8.3.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.1.2=py38h06a4308_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jsonschema=4.16.0=py38h06a4308_0
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyter_server=1.18.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - kiwisolver=1.4.2=py38h295c915_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.8=h780b84a_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h2818925_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - locket=1.0.0=py38h06a4308_0
  - lxml=4.9.1=py38h1edc446_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.7=pyhd8ed1ab_0
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=6.0.2=py38h0a891b7_1
  - munkres=1.1.4=py_0
  - nbclassic=0.4.8=py38h06a4308_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.5.4=py38h06a4308_0
  - nbformat=5.5.0=py38h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.2=py38h06a4308_0
  - notebook-shim=0.2.2=py38h06a4308_0
  - numpy-base=1.22.3=py38hf524024_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=21.2.4=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.3.0=py38h7f8727e_0
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.8=pyhd8ed1ab_0
  - scikit-image=0.19.2=py38h51133e4_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.7.3=py38hc147768_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py38h06a4308_1
  - soupsieve=2.3.2.post1=py38h06a4308_0
  - sqlite=3.38.3=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py38h2b5fc30_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.13.1=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.11=h1ccaba5_1
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py38_cu113
  - torchmetrics=0.9.0=pyhd8ed1ab_0
  - torchvision=0.12.0=py38_cu113
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - urllib3=1.26.9=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.7.2=py38h0a891b7_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.1.0
    - appdirs==1.4.4
    - argcomplete==2.0.0
    - bagit==1.8.1
    - bashlex==0.16
    - btrees==4.11.3
    - cachecontrol==0.12.11
    - cachetools==5.2.0
    - calamus==0.4.1
    - click-option-group==0.5.5
    - click-plugins==1.1.1
    - coloredlogs==15.0.1
    - commonmark==0.9.1
    - coverage==6.4.4
    - cwl-upgrader==1.2.4
    - cwl-utils==0.17
    - cwltool==3.1.20220628170238
    - deepdiff==5.8.1
    - deepmerge==1.0.1
    - docker==5.0.3
    - docker-pycreds==0.4.0
    - dunamai==1.15.0
    - efficientnet-pytorch==0.7.1
    - filelock==3.8.0
    - frozendict==2.3.4
    - fsspec==2022.5.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - grad-cam==1.3.9
    - grandalf==0.7
    - grpcio==1.46.3
    - huggingface-hub==0.12.0
    - humanfriendly==10.0
    - humanize==4.0.0
    - importlib-resources==5.9.0
    - inject==4.3.1
    - isodate==0.6.1
    - lockfile==0.12.2
    - marshmallow==3.19.0
    - mistune==2.0.4
    - msgpack==1.0.4
    - munch==2.5.0
    - networkx==2.6.3
    - numpy==1.21.6
    - opencv-python==4.6.0.66
    - ordered-set==4.1.0
    - owlrl==6.0.2
    - pathtools==0.1.2
    - patool==1.12
    - persistent==5.0
    - pluggy==1.0.0
    - poetry-dynamic-versioning==0.21.3
    - portalocker==2.4.0
    - pretrainedmodels==0.7.4
    - prettytable==2.5.0
    - promise==2.3
    - protobuf==3.20.1
    - prov==1.5.1
    - psutil==5.9.1
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pyld==2.0.3
    - pyparsing==3.0.9
    - pyshacl==0.18.1
    - python-editor==1.0.4
    - python-gitlab==3.8.1
    - pytorch-lightning==1.6.4
    - pyyaml==6.0
    - rdflib==6.1.1
    - renku==2.1.0
    - requests-toolbelt==0.10.1
    - rich==12.5.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - schema-salad==8.3.20230109181936
    - segmentation-models-pytorch==0.3.2
    - sentry-sdk==1.6.0
    - setproctitle==1.2.3
    - shellescape==3.8.1
    - shellingham==1.5.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tabulate==0.8.10
    - termcolor==1.1.0
    - timm==0.6.12
    - tomlkit==0.11.6
    - tqdm==4.62.3
    - transaction==3.0.1
    - ttach==0.0.3
    - wandb==0.13.9
    - yagup==0.1.1
    - yaspin==2.1.0
    - zc-lockfile==2.0
    - zc-relation==1.1.post2
    - zconfig==3.6.1
    - zdaemon==4.4
    - zeo==5.4.0
    - zodb==5.6.0
    - zodb3==3.11.0
    - zodbpickle==2.6
    - zope-interface==5.5.2
    - zope-testing==5.0.1
    - zstandard==0.17.0
prefix: /data/users/michele/miniconda3/envs/mzbfull
