name: mzb-forge
channels:
  - pytorch
  - nvidia
  - conda-forge
  # - defaults
dependencies:
  - python=3.10
  - numpy=1.25
  - pandas=1.5.3
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - pytorch-lightning=2.0.3
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - scikit-image=0.20.0
  - ipython=8.12.0
  - ipykernel=6.25.0
  - pip
  - pip:
    - pyyaml==6.0
    - wandb==0.15.8
    - opencv-python==4.8.0.76
    - segmentation_models_pytorch==0.3.3
    - sphinx-rtd-theme==1.2.2
    - tensorboard==2.13.0
    - tensorboardX==2.6.2
