[[pages]]
path = "streamlit_pages/app_homepage.py"
name = "mzbsuite"
icon = "ğŸ "
# url_path = "my_books" # You can override the default url path for a page

[[pages]]
name = "Segmentation"
icon = "ğŸ§©"
is_section = true

    [[pages]]
    path = "streamlit_pages/app_main_raw_to_clips.py"
    name = "Segmentation unsupervised"
    icon = "ğŸ§©"
    # url_path = "my_books" # You can override the default url path for a page

[[pages]]
name = "Skeletonization"
icon = "ğŸ¦´"
is_section = true

    [[pages]]
    path = "streamlit_pages/app_main_unsupervised_skeleton_estimation.py"
    name = "Skeletonization unsupervised"
    icon = "ğŸ¦´"

    [[pages]]
    path = "streamlit_pages/app_main_supervised_skeleton_inference.py"
    name = "Skeletonization supervised - inference"
    icon = "ğŸ¦´"

    [[pages]]
    path = "streamlit_pages/app_main_supervised_skeletons_finetune.py"
    name = "Skeletonization supervised - finetuning"
    icon = "ğŸ¦´"

    # [[pages]]
    # path = "streamlit_pages/app_main_supervised_skeleton_assessment.py"
    # name = "Skeletonization supervised - assessment"
    # icon = "ğŸ¦´"

[[pages]]
name = "Classification"
icon = "ğŸ—‚ï¸"
is_section = true

    [[pages]]
    path = "streamlit_pages/app_main_classification_inference.py"
    name = "Classification - inference"
    icon = "ğŸ—‚ï¸"

    [[pages]]
    path = "streamlit_pages/app_main_classification_finetune.py"
    name = "Classification - finetuning"
    icon = "ğŸ—‚ï¸"

[[pages]]
name = "Other utiities"
icon = "ğŸ› ï¸"
is_section = true

    [[pages]]
    path = "streamlit_pages/app_main_prepare_learning_sets.py"
    name = "Prepare learning sets"
    icon = "ğŸ› ï¸"

    [[pages]]
    path = "streamlit_pages/app_main_preprocess_manual_skeleton_annotations.py"
    name = "Pre-process manual skeleton annotations"
    icon = "ğŸ› ï¸"